### ISSUE TITLE
WarehousesGetRequest - missing field WarehouseId and Limit

### ISSUE THREAD

**Issue by Alikont** [iAlexeyProkhorov/Baroque.NovaPoshta.Client#10]
[Documentation](https://developers.novaposhta.ua/view/model/a0cf0f5f-8512-11ec-8ced-005056b2dbe1/method/a2322f38-8512-11ec-8ced-005056b2dbe1).

Missing fields:

```csharp
    [DataMember]
    public string? WarehouseId { get; set; }
    [DataMember]
    public int? Limit { get; set; }
```

Also field `Page` is missing `[DataMember]` attribute, so it is not being serialized.

**Comment by iAlexeyProkhorov** [comment]
Hi, @Alikont !
Thank you for your message. I'll try to fix this request today.

**Comment by iAlexeyProkhorov** [comment]
Hi, @Alikont !
Project upgraded to version 1.4.1 and contains fix for this issue.

P. S.
Sorry for two weeks delay😐
